### ISSUE TITLE
Detect when GitLab is down

### ISSUE THREAD

**Issue by jayvdb** [ksdme/org-status#5]
https://status.gitlab.com/ & https://api.status.io/1.0/status/5b36dc6502d06804c08349f7

The program should detect when GitLab systems are not operating well , and report that as a simple status. Use the JSON API endpoint mentioned above to get a machine readable version of GitLab status.

# NOTE FOR GCI STUDENTS
You'll also have to solve https://github.com/ksdme/org-status/issues/24 in which you need to add CLI interface to existing modes.

**Comment by arihantbansal** [comment]
Would a stand alone Python program suffice? I've already written one. Just asking if I can submit it.

**Comment by arihantbansal** [comment]
Okay.

**Comment by ksdme** [comment]
I did some research on how Gitlab's status page at status.gitlab.com works, turns out they use status.io. So, here we have the JSON API endpoint to get Gitlab's Status https://api.status.io/1.0/status/5b36dc6502d06804c08349f7

**Comment by ksdme** [comment]
You'll also have to solve #24 in which you need to add CLI interface to existing modes.

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [4663390120181760](https://codein.withgoogle.com/dashboard/tasks/4663390120181760).
